spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: userservice
          uri: lb://USERSERVICE
          predicates:
            - Path=/userservice/**
            - Method=GET
          filters:
            - RewritePath=/userservice/(?<segment>.*), /$\{segment}
        ##회원가입
        - id: userservice
          uri: lb://USERSERVICE
          predicates:
            - Path=/userservice/**
            - Method=POST
          filters:
            - RewritePath=/userservice/(?<segment>.*), /$\{segment}
        - id: userservice
          uri: lb://USERSERVICE
          predicates:
            - Path=/userservice
            - Method=GET
          filters:
            - RewritePath=/userservice, /
server:
  port: 8000
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
