spring:
  application:
    name: userservice
  r2dbc:
    url: r2dbc:pool:mariadb://localhost:3307/webflux
    username: root
    password: 123qwe
#    pool:
#      enabled: true
#      initial-size: 10
#      max-acquire-time: 5s
#      max-create-connection-time: 5s
#      max-idle-time: 60m
#      max-life-time: 60m
#      max-size: 10

logging:
  level:
    io.r2dbc.pool: DEBUG
    reactor.pool: DEBUG
    #org.springframework.r2dbc.core.DefaultDatabaseClient: debug

server:
  port: 0
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
